version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 52c97c4e33de0c84d6322f78c932ceafcd7b54a5
=======
>>>>>>> 52c97c4e33de0c84d6322f78c932ceafcd7b54a5
            MYSQL_ROOT_PASSWORD: R1234r
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: clarusway
            MYSQL_PASSWORD: Clarusway_1
        networks:
            - clarusnet
    myapp:
        build: .
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> e4d47162a527adb7bbb6d4e17844506122c3a21d
            MYSQL_ROOT_PASSWORD: P123456p
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: clarusway
            MYSQL_PASSWORD: Clarusway_1 
        networks:
            - clarusnet
    myapp:
        image: callahanclarus/bookstore-api:latest
<<<<<<< HEAD
>>>>>>> 5a1c9f02536c3014ed2890184331e4ede12e11fb
=======
>>>>>>> 52c97c4e33de0c84d6322f78c932ceafcd7b54a5
=======
>>>>>>> 52c97c4e33de0c84d6322f78c932ceafcd7b54a5
=======
>>>>>>> e4d47162a527adb7bbb6d4e17844506122c3a21d
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - clarusnet
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD

=======
>>>>>>> 5a1c9f02536c3014ed2890184331e4ede12e11fb
=======

>>>>>>> 52c97c4e33de0c84d6322f78c932ceafcd7b54a5
=======

>>>>>>> 52c97c4e33de0c84d6322f78c932ceafcd7b54a5
=======
>>>>>>> e4d47162a527adb7bbb6d4e17844506122c3a21d
networks:
    clarusnet:
        driver: bridge